action/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^(?P<user_id>\d+)$',views.action,name='action'),
]

blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^users/',include('users.urls',namespace='users')),
	url(r'^users/', include('django.contrib.auth.urls')),
	url(r'^comments/',include('comments.urls',namespace='comments')),
	url(r'^message/',include('message.urls',namespace='message')),
	url(r'^notes/',include('notes.urls',namespace='notes')),
	url(r'^action/',include('action.urls',namespace='action')),
	url(r'',include('blogs.urls',namespace='blogs')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required

urlpatterns=[
	url(r'^$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^index/$',views.index,name='index'),
	# url(r'^index/$',login_required(views.IndexView.as_view()),name='index'),
	url(r'^themes/(?P<user_id>\d+)/$',views.themes,name='themes'),
	# url(r'^themes/(?P<user_id>\d+)/$',views.ThemesView.as_view(),name='themes'),
	url(r'^themes/(?P<user_id>\d+)/(?P<theme_id>\d+)/$',views.theme,name='theme'),
	url(r'^new_theme/$',views.new_theme,name='new_theme'),
	url(r'^new_note/(?P<theme_id>\d+)/$',views.new_note,name='new_note'),
	url(r'^delete_theme/(?P<theme_id>\d+)/$',views.delete_theme,name='delete_theme'),
	url(r'^delete_note/(?P<theme_id>\d+)/(?P<note_id>\d+)/$',views.delete_note,name='delete_note'),
	url(r'^(?P<theme_id>\d+)/privacy/$',views.privacy,name='privacy'),
	url(r'^search/$',views.search,name='search'),
	url(r'^themes/(?P<user_id>\d+)/(?P<theme_id>\d+)/give_praise/$',views.give_praise,name='give_praise'),
	url(r'^themes/(?P<user_id>\d+)/(?P<theme_id>\d+)/get_favorite/$',views.get_favorite,name='get_favorite'),
	url(r'^test/$',views.test,name='test'),
]

message/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^(?P<user_id>\d+)/$',views.message,name='message'),
	url(r'^message_privacy/$',views.message_privacy,name='message_privacy'),
	url(r'^delete/(?P<user_id>\d+)/(?P<message_id>\d+)/$',views.message_delete,name='message_delete'),
]

notes/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^notes/$',views.notes,name='notes')
]

users/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

urlpatterns=[
	url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^logout/$',views.logout_views,name='logout'),
	url(r'^register/$',views.register,name='register'),
	url(r'^some_works/$',views.some_works,name='some_works'),
	url(r'^register_confirm/$',views.register_confirm,name='register_confirm'),
	url(r'^userinfo/(?P<user_id>\d+)/$',views.userinfo,name='userinfo'),
	url(r'^news/$',views.news,name='news'),
	url(r'^user_ff_list/(?P<user_id>\d+)/',views.ff_list,name='ff_list'),
	url(r'^alterinfo/$',views.alterinfo,name='alterinfo'),
	url(r'^regsuc/$',views.regsuc,name='regsuc'),
	url(r'^follow/(?P<user_id>\d+)/$',views.follow,name='follow'),
	url(r'^favorite_list/(?P<user_id>\d+)/$',views.favorite_list,name='favorite_list'),
	
]

blogs/models.py
from django.db import models
from django.contrib.auth.models import User

class Theme(models.Model):
	owner=models.ForeignKey(User)
	title=models.CharField('标题',max_length=20)
	date_added=models.DateTimeField(auto_now_add=True)
	date_updated=models.DateTimeField(auto_now=True)
	设为私密=models.BooleanField(default=False)
	views=models.PositiveIntegerField(default=0)
	praises=models.PositiveIntegerField(default=0)
	
	def increase_praises(self):
		self.praises+=1
		self.save(update_fields=['praises'])
	def increase_views(self):
		self.views+=1
		self.save(update_fields=['views'])
	def __str__(self):
		return self.title
		
class Note(models.Model):
	title=models.ForeignKey(Theme)
	text=models.TextField('写下....')
	date_added=models.DateTimeField(auto_now_add=True)
	def __str__(self):
		return self.title.title
	

blogs/forms.py
from django import forms
from .models import Theme,Note

class ThemeForm(forms.ModelForm):
	class Meta:
		model=Theme
		fields=['title','设为私密']
		lables={}


class NoteForm(forms.ModelForm):
	class Meta:
		model=Note
		fields=['text']
		lables={'text':''}
		widgets={'text':forms.Textarea(attrs={'cols':80})}

blogs/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .models import Theme,Note
from users.models import Userinfo,Favorites
from comments.models import Comment
from .forms import NoteForm,ThemeForm
from comments.forms import CommentForm
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.decorators.cache import cache_page
from django.contrib.auth.decorators import login_required
from django.db.models import Q
from django.views.generic import ListView

@login_required
def index(request):
	try:
		sort=request.GET['sort']
		themes=Theme.objects.filter(设为私密=False).order_by('-'+sort)
	except:
		themes=Theme.objects.filter(设为私密=False).order_by('-date_added')
	page_user=request.user
	context={'themes':themes,'page_user':page_user}
	return render(request,'blogs/index.html',context)

# class IndexView(ListView): #基于类的视图
	# model=Theme
	# template_name='blogs/index.html'
	# context_object_name='themes'
	# def get_queryset(self):
		# try:
			# sort=self.request.GET['sort']
			# return super().get_queryset().filter(设为私密=False).order_by('-'+sort)
		# except:
			# return super().get_queryset().filter(设为私密=False).order_by('-date_added')
	# def get_context_data(self,**kwargs):
		# context=super().get_context_data(**kwargs)
		# page_user=self.request.user
		# context.update({'page_user':page_user})
		# return context

@login_required
def themes(request,user_id):
	request_user=request.user
	page_user=get_object_or_404(User,id=user_id)
	if page_user==request_user:
		themes=Theme.objects.filter(owner=request.user).order_by('date_added')
	else:
		themes=Theme.objects.filter(owner=page_user,设为私密=False).order_by('date_added')
	context={'themes':themes,'page_user':page_user,'request_user':request_user}
	return render(request,'blogs/themes.html',context)
	
# class ThemesView(ListView):    #基于类
	# model=Theme
	# template_name='blogs/themes.html'
	# context_object_name='themes'
	# def get_context_data(self,**kwargs):
		# context=super().get_context_data(**kwargs)
		# request_user=self.request.user
		# page_user=get_object_or_404(User,id=self.kwargs.get('user_id'))
		# if page_user==request_user:
			# themes=Theme.objects.filter(owner=request_user).order_by('date_added') 
		# else:
			# themes=Theme.objects.filter(owner=page_user,设为私密=False).order_by('date_added')
		# context.update({'request_user':request_user,'themes':themes,'page_user':page_user})
		# return context
	
@login_required
def theme(request,user_id,theme_id):
	request_user=request.user
	page_user=get_object_or_404(User,id=user_id)
	theme=get_object_or_404(Theme,id=theme_id)
	theme.increase_views()
	
	if theme.设为私密==True:
		if theme.owner!=request_user:
			return Http404
	notes=Note.objects.filter(title=theme).order_by('date_added')
	
	comment_form=CommentForm()
	comments=theme.comment_set.order_by('date_added')
	#分页:
	    #note
	notes_pages=Paginator(notes,5)
	page_num_notes=request.GET.get('page_n')
	try:
		notes_page=notes_pages.page(page_num_notes)
	except PageNotAnInteger:
		notes_page=notes_pages.page(1)
	except EmptyPage:
		notes_page=notes_pages.page(notes_pages.num_pages)
	    #comment
	comments_pages=Paginator(comments,5)
	page_num_comments=request.GET.get('page_c')
	
	try:
		favorite=Favorites.objects.get(user=request_user,theme=theme)
		is_favo=True
	except:
		is_favo=False
	
	context={'theme':theme,'page_user':page_user,'request_user':request_user,'comments':comments,'notes_page':notes_page,'notes_pages':notes_pages,'comment_form':comment_form,'is_favo':is_favo}
	return render(request,'blogs/theme.html',context)
@login_required
def new_theme(request):
	if request.method!='POST':
		form=ThemeForm()
	else:
		form=ThemeForm(data=request.POST)
		user_id=request.user.id
		if form.is_valid():
			new_theme=form.save(commit=False)
			new_theme.owner=request.user
			new_theme.save()
			return HttpResponseRedirect(reverse('blogs:themes',args=[user_id]))
	page_user=request.user
	context={'form':form,'page_user':page_user}
	return render(request,'blogs/new_theme.html',context)
@login_required
def new_note(request,theme_id):
	theme=Theme.objects.get(id=theme_id)
	if request.method!='POST':
		form=NoteForm()
	else:
		user_id=request.user.id
		form=NoteForm(data=request.POST)
		if form.is_valid():
			new_note=form.save(commit=False)
			new_note.title=theme
			new_note.save()
			return HttpResponseRedirect(reverse('blogs:theme',args=[user_id,theme_id]))
	page_user=request.user
	context={'theme':theme,'form':form,'page_user':page_user}
	return render(request,'blogs/new_note.html',context)
@login_required
def delete_theme(request,theme_id):
	Theme.objects.get(id=theme_id).delete()
	user_id=request.user.id
	return HttpResponseRedirect(reverse('blogs:themes',args=[user_id]))
@login_required
def delete_note(request,theme_id,note_id):
	theme=Theme.objects.get(id=theme_id)
	theme.note_set.get(id=note_id).delete()
	user_id=request.user.id
	return HttpResponseRedirect(reverse('blogs:theme',args=[user_id,theme_id]))
@login_required
def privacy(request,theme_id):
	theme=Theme.objects.get(id=theme_id)
	if theme.设为私密:
		theme.设为私密=False
		theme.save()
	else:
		theme.设为私密=True
		theme.save()
	page_user=request.user
	context={'page_user':page_user}
	return render(request,'blogs/privacysuc.html',context)
@login_required
def search(request):
	page_user=request.user
	search=request.POST.get('search')
	if not search:
		error_msg='请输入关键词'
		return render(request,'blogs/index.html',{'error_msg':error_msg,'page_user':page_user})
	theme_list=Theme.objects.filter(Q(title__icontains=search)).filter(设为私密=False)
	user_list=User.objects.filter(Q(username__icontains=search))
	user_id_list=User.objects.filter(Q(id__icontains=search))
	context={'theme_list':theme_list,'user_list':user_list,'page_user':page_user,'user_id_list':user_id_list}
	return render(request,'blogs/search.html',context)
def give_praise(request,user_id,theme_id):
	if request.is_ajax():
		try:
			theme=Theme.objects.get(id=theme_id)
			theme.increase_praises()
			praises=theme.praises
			return HttpResponse(praises)
		except:
			return HttpResponse('主题不存在')
def get_favorite(request,user_id,theme_id):
	if request.is_ajax():
		user=request.user
		theme=Theme.objects.get(id=theme_id)
		try:
			favorite=Favorites.objects.get(user=user,theme=theme)
			favorite.delete()
			return HttpResponse('取消收藏!')
		except:
			Favorites.objects.create(user=user,theme=theme)
			return HttpResponse('收藏成功!')
	
def test(request):
	user=request.user
	userinfo=Userinfo.objects.get(user=user)
	years=range(1980,2020)
	colors=request.GET.getlist('colors')
	color=request.GET.get('color')
	try:
		user_id=request.GET['user_id']
		user_pass=request.GET['user_pass']
	except:
		user_id=None
	if user_id!=None and user_pass=='123':
		verified=True
	else:
		verified=False
	page_user=request.user
	return render(request,'blogs/test.html',locals())

blogs/templates/blogs/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang='en'>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1, user-scalable=no'>
	
  <title>zz' website</title>
	
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body><!-- Static navbar -->
  <nav class='navbar navbar-default navbar-static-top'>
    <div class='container'>
	  <div class='navbar-header'> 
		<button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded= 'false' aria-controls='navbar'>
		</button>
	    <a class='navbar-brand' href="{% url 'blogs:index' %}"><!-- <img src="{% static 'images/index.jpg' %}"/> -->seLzzf</a>
		
	  </div>
	  
	  <div id='navbar' class='navbar-collapse collapse'>
	    <ul class='nav navbar-nav'>
		  <li><a href="{% url 'blogs:themes' page_user.id %}">我的主题</a></li>
		  {% if user == page_user %}
		  <li><a href="{% url 'action:action' user.id %}">我的关注</a></li>
		  {% endif %}
		  <li><a href="{% url 'message:message' page_user.id %}">留言板</a></li>
		  <li><a href="{% url 'blogs:test' %}">test</a></li>
		  {% if user.is_superuser %}
		    <li><a class='navbar-brand' href="{% url 'notes:notes' %}">学习笔记</a></li>
		  {% endif %}
		  <li style='margin-top:10px' class='search'> 
		    <form method='post' action="{% url 'blogs:search' %}">
			{% csrf_token %}
		    <input name='search' type='search' placeholder='搜索关键字/用户'/>
		    <input class='btn' type='submit' value='搜索'>
		    </form>
		  </li>
		</ul>
		<ul class='nav navbar-nav navbar-right'>
		  {% if user.is_authenticated %}
			<li><a href="{% url 'users:userinfo' user.id %}">Hello,{{ user.username }}.</a></li>
			<li><a href="{% url 'users:news' %}">我的消息</a></li>
			<li><img style='margin-top:5px' src="{{ request_userinfo.pic.url }}" alt='pic' height="40" width="40"/></li>
			<li><a href="{% url 'users:logout' %}">退出</a></li>
		  {% endif %}
		</ul> 
	  </div><!--/.nav-collapse --> 
	</div>  
  </nav>
  <div class='container'>
    <div class='page-header'>
      {% block header %}{% endblock header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
	</div>
  </div><!-- /container --> 
</body>

</html>

blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}
{% load static %}
{% block header %}
  <h3>随便看看:</h3>
{% endblock header %}

{% block content %}

<div><h3>
  <table class='table table-hover table-striped'>
    <thead>
	  <tr>
	    <th>文章</th>
		<th>&nbsp </th>
		<th>浏览 <a href="?sort=views">↓</a></th>
		<th>发表日期 <a href="?sort=date_added">↓</a></th>
	  </tr>
	</thead>
	<tbody>
	  {% for theme in themes %}
	  <tr>
		<td>
		  <a style='color:#777' href="{% url 'blogs:theme' theme.owner.id theme.id %}">{{theme.title}}</a>
		</td>
		<td>
		  <a style='color:#777' href="{% url 'users:userinfo' theme.owner.id %}">{{theme.owner}}</a>
		</td>
		<td>
		  <img src="{% static 'images/views.jpg' %}"/>{{theme.views}}
		</td>
		<td>{{theme.date_added|date:'m-d'}}</td>
	  </tr>
	  {% empty %}
	    <h3>服务器好像出错了,请刷新重试或诊断网络</h3>
	  {% endfor %}
	</tbody>
</h3></div>

  {% if page_user == user %}
  <h3>
    <a href="{% url 'blogs:new_theme' %}">添加主题</a>
  </h3>
  {% endif %}
</div>  
{% endblock content %}

blogs/templates/blogs/new_note.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h3>{{theme}}:<h3>
{% endblock header %}

{% block content %}

<h4><p>add your note in here:</p><h4>
<form action="{% url 'blogs:new_note' theme.id %}" method='post' class='form'>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
  <button name='submit' class='btn btn-primary'>OK</button>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/new_theme.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}

{% block header %}
  <h3>主题/文章/心情:</h3>
{% endblock header %}

{% block content %}
<form method='post' action="{% url 'blogs:new_theme' %}" class='form'>
  {% csrf_token %}
  {% bootstrap_form form %}
  {% buttons %}
    <button name='submit' class='btn btn-primary'>提交</button>
  {% endbuttons %}
</form>

{% endblock content %}

blogs/templates/blogs/privacysuc.html
{% extends 'blogs/base.html' %}

{% block header %}<h4>权限修改成功<h4>{% endblock header %}
{% block content %}
<a href="{% url 'blogs:index' %}">返回主页</a>
{% endblock content %}

blogs/templates/blogs/search.html
{% extends 'blogs/base.html' %}
{% block header %}{% endblock header %}

{% block content %}

<h3>在主题/书名中搜索结果:</h3>
{% for search_theme in theme_list %}
  <li>
    <a href="{% url 'blogs:theme' search_theme.owner.id search_theme.id %}">{{search_theme.title}}</a>
  </li>
{% empty %}
  <p>抱歉，没有搜索到相关结果。</p>
{% endfor %}

<h3>在用户名中搜索结果:</h3>
{% for search_user in user_list %}
  <li>
    <a href="{% url 'users:userinfo' search_user.id %}">{{search_user.username}}</a>
  </li>
{% empty %}
  <p>抱歉，没有搜索到相关结果。</p>
{% endfor %}

<h3>在用户ID中搜索结果:</h3>
{% for search_user in user_id_list %}
  <li><a href="{% url 'users:userinfo' search_user.id %}">{{search_user.username}}</a></li>
{% empty %}
  <p>抱歉，没有搜索到相关结果。</p>
{% endfor %}

{% endblock content %}

blogs/templates/blogs/test.html
{% extends 'blogs/base.html' %}
{% load bootstrap3 %}
{% load static %}

{% block header %}Test{% endblock header %}

{% block content %}

<div class='container'>

  <form name='my form' action="{% url 'blogs:test' %}" method='GET'>
  <div>
    <label for='user_id'>Your ID:</label>
	<input class='form-control' id='user_id' type='text' name='user_id'>
	<label for='user_pass'>Your password:</label>
	<input id='user_pass' type='password' name='user_pass'>
    <button name='submit' class='btn btn-primary active' disabled='disabled'>OK</button>
  </div>
  </form>
  
<br/>
  <div>	
	<label for='byear'>出生日期:</label>
    <select name='byear'>
      {% for year in years %}
        <option value='{{ year }}'>{{ year }}</option>
	  {% endfor %}
    </select><br/>
  </div>
  <div>
	<input type='checkbox' name='colors' value='Green'>Green
	<input type='checkbox' name='colors' value='red'>red
	<input type='checkbox' name='colors' value='blue'>blue
	<input type='checkbox' name='colors' value='yellow'>yellow
	<br/>
  </div>
  <div>
	<input type='radio' name='color' value='Green'>Green
	<input type='radio' name='color' value='red'>red
	<input type='radio' name='color' value='blue'>blue
	<input type='radio' name='color' value='black'>black
	<br/>
  </div>
  <div>
	<input type='reset' value='重置信息'>
	<input type='submit' value='登录'>
	<br/>
  </div>

  </form>
  <div>
    Your ID:{{ user_id | default:'未输入ID' }} <br/>
    多选框输入:
    {% for color in colors %}
    {{ color }}
    {% empty %}
    None 
    {% endfor %}
  </div>
  <div>
    单选框输入:
    {{ color }}
  </div>
  <div>
    {% if verified %}
      <em>成功登录</em>
    {% else %}
      <em>登录失败</em>
    {% endif %}
  </div>



</div>

{% endblock content %}

blogs/templates/blogs/theme.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}
{% load static %}
{% block header %}
  <h3>{{ theme.title }}:</h3>
  <h4>
  <li style='display:inline-block'>浏览:{{theme.views}} &nbsp </li>
  <li style='display:inline-block'>评论:{{comments.count}} &nbsp </li>
  <li id='praise' style='display:inline-block'>点赞数:{{theme.praises}}</li>
  {% if is_favo %}
  <a><img style="float:right;" id='favorite' src="{% static 'images/favorite2.png' %} " alt='is' /></a>
  {% else %}
  <a><img style="float:right;" id='favorite' src="{% static 'images/favorite1.png' %}" alt='isnot' /></a>
  {% endif %}
  <img style="float:right;padding-right:15px" id='praise_pic' src="{% static 'images/praise1.png' %}"/>
  </h4>
  
{% endblock header %}

{% block content %}
<div class="col-md-8">
  <p><h4>
    {% if page_user == request_user %}
      <a href="{% url 'blogs:new_note' theme.id %}">添加..</a>
      {% if theme.设为私密 %}
        <a href="{% url 'blogs:privacy' theme.id %}">设为公开</a>
      {% else %}
        <a href="{% url 'blogs:privacy' theme.id %}">设为私密</a> 
      {% endif %}
    {% endif %}
  </h4></p>
  
{% for note in notes_page %}
  <div class='panel panel-default'>
    <div class='panel-body'>
	  <h4>{{ note.text|linebreaks }}</h4>
    </div>
    <div class='panel-heading'>
        {{note.date_added|date:'Y-m-d H:i:s'}} &nbsp
	  {% if page_user == request_user %}
	    <a style="float:right;" href="{% url 'blogs:delete_note' theme.id note.id %}">删除</a>
	  {% endif %}
    </div>
  </div>
{% empty %}
  <h3><li>there have no note in here.let's add your first note!</li></h3>
{% endfor %}
</div>

<div class="col-md-4">
  <h4>评论:</h4>
  {% for comment in comments %}
  <div class='panel panel-default'>
    <div class='panel-body'>
	  <h4>
      {{ comment.message|linebreaks }}</hr>
	  </h4>
    </div>
    <div class='panel-heading'>
	   <a href="{% url 'users:userinfo' comment.publisher.id %}">{{comment.publisher}}</a>
      <div style="float:right;">{{comment.date_added|date:'Y-m-d H:i:s'}}
	  &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
	  {% if page_user == request_user %}
	    <a href="">删除</a>
	  {% endif %}
      </div>
    </div>
  </div>

  {% empty %}
  <h3><li>暂时还没有评论。</li></h3>
  {% endfor %}
  
  <div>
  <h4>发表评论:</h4>
  <form method='POST' action="{% url 'comments:handle_comment' theme.id %}">
    {% csrf_token %}
    {% bootstrap_form comment_form %}
    {% buttons %}
	<button name='submit' class='btn btn-primary'>提交</button>
	{% endbuttons %}
  </form>
  </div>
  
</div>

<div class='pagination col-md-12'>
  {% if notes_page.has_previous %}
    <a href="?page_n={{ notes_page.previous_page_number }}">上一页</a>
  {% endif %}
  <span class='current'>第{{ notes_page.number }}页/共{{ notes_pages.num_pages }}页</span>
  {% if notes_page.has_next %}
    <a href="?page_n={{ notes_page.next_page_number }}">下一页</a>
  {% endif %}
</div>

<script src="{% static 'js/test.js' %}"></script>

{% endblock content %}

blogs/templates/blogs/themes.html
{% extends "blogs/base.html" %}
{% block header %}
  {% if page_user == request_user %}
  <h3>我的主题:</h3>
  {% elif request_userinfo.sex == '男' %}
      <h3>他的主题:</h3>
  {% else %}
      <h3>她的主题:</h3>
  {% endif %}
{% endblock header %}

{% block content %}
<div class="col-md-7">
<ul>
  {% for theme in themes %}
	<li>
	<h3><a href="{% url 'blogs:theme' page_user.id theme.id %}">{{theme.title}}</a>
	<div style="float:right;">
	    &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp
		{{theme.date_added|date:'m-d'}}
	</div>
  {% if page_user == request_user %}
	<a style="float:right;" href="{% url 'blogs:delete_theme' theme.id %}">删除</a>
	</li>
  {% endif %}
  </h3>
  {% empty %}
	<li>赶紧写下你的第一个主题吧。<li>
  {% endfor %}
</ul>
<h3>
  {% if page_user == user %}
    <a href="{% url 'blogs:new_theme' %}">添加书籍/主题</a>
  {% endif %}
</h3>
</div>
{% endblock content %}