blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^users/',include('users.urls',namespace='users')),
	url(r'^users/', include('django.contrib.auth.urls')),
	url(r'^comments/',include('comments.urls',namespace='comments')),
	url(r'^message/',include('message.urls',namespace='message')),
	url(r'^notes/',include('notes.urls',namespace='notes')),
	url(r'^action/',include('action.urls',namespace='action')),
	url(r'',include('blogs.urls',namespace='blogs')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login
from django.contrib.auth.decorators import login_required

urlpatterns=[
	url(r'^$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^index/$',views.index,name='index'),
	# url(r'^index/$',login_required(views.IndexView.as_view()),name='index'),
	url(r'^themes/(?P<user_id>\d+)/$',views.themes,name='themes'),
	# url(r'^themes/(?P<user_id>\d+)/$',views.ThemesView.as_view(),name='themes'),
	url(r'^themes/(?P<user_id>\d+)/(?P<theme_id>\d+)/$',views.theme,name='theme'),
	url(r'^new_theme/$',views.new_theme,name='new_theme'),
	url(r'^new_note/(?P<theme_id>\d+)/$',views.new_note,name='new_note'),
	url(r'^delete_theme/(?P<theme_id>\d+)/$',views.delete_theme,name='delete_theme'),
	url(r'^delete_note/(?P<theme_id>\d+)/(?P<note_id>\d+)/$',views.delete_note,name='delete_note'),
	url(r'^(?P<theme_id>\d+)/privacy/$',views.privacy,name='privacy'),
	url(r'^search/$',views.search,name='search'),
	url(r'^themes/(?P<user_id>\d+)/(?P<theme_id>\d+)/give_praise/$',views.give_praise,name='give_praise'),
	url(r'^themes/(?P<user_id>\d+)/(?P<theme_id>\d+)/get_favorite/$',views.get_favorite,name='get_favorite'),
	url(r'^test/$',views.test,name='test'),
]

users/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

urlpatterns=[
	url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^logout/$',views.logout_views,name='logout'),
	url(r'^register/$',views.register,name='register'),
	url(r'^some_works/$',views.some_works,name='some_works'),
	url(r'^register_confirm/$',views.register_confirm,name='register_confirm'),
	url(r'^userinfo/(?P<user_id>\d+)/$',views.userinfo,name='userinfo'),
	url(r'^news/$',views.news,name='news'),
	url(r'^user_ff_list/(?P<user_id>\d+)/',views.ff_list,name='ff_list'),
	url(r'^alterinfo/$',views.alterinfo,name='alterinfo'),
	url(r'^regsuc/$',views.regsuc,name='regsuc'),
	url(r'^follow/(?P<user_id>\d+)/$',views.follow,name='follow'),
	url(r'^favorite_list/(?P<user_id>\d+)/$',views.favorite_list,name='favorite_list'),
	
]

users/models.py
from django.db import models
from django.contrib.auth.models import User
from blogs.models import Theme

class Userinfo(models.Model):
	user=models.OneToOneField(User)
	pic=models.ImageField(upload_to='images',default='images/default.jpg',verbose_name='头像',blank=True)
	sex=models.CharField('性别',max_length=2,choices=(
	('男','♂'),('女','♀')),blank=True)
	birthday=models.DateField('生日',default='2000-01-01',blank=True)
	school=models.TextField('学校',max_length=50,default='暂未设置所在学校')
	autograph=models.TextField('个性签名',max_length=50,default='暂未设置个性签名')
	
	def __str__(self):
		return self.user.username

class YZM(models.Model):
	email=models.EmailField(blank=True)
	yzm=models.IntegerField(blank=True,default=123456)
	
	def __str__(self):
		return str(self.yzm)
		
class Follower(models.Model):
	focus=models.ForeignKey(User,related_name='focus')
	follower=models.ForeignKey(User,related_name='follower',blank=True)
		
class News(models.Model):
	user=models.ForeignKey(User)
	news=models.TextField('消息',blank=True)
	status=models.BooleanField(default=True)
	date_added=models.DateTimeField(auto_now_add=True,blank=True)

class Favorites(models.Model):
	user=models.ForeignKey(User)
	theme=models.ForeignKey(Theme)

users/forms.py
from django.forms import ModelForm,Textarea,IntegerField,Form,TextInput
from .models import Userinfo
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserForm(UserCreationForm):
	class Meta(UserCreationForm.Meta):
		model=User
		fields=['username']
		
class UserProfileForm(ModelForm):
	class Meta:
		model=Userinfo
		fields=['birthday','sex','school','autograph','pic']
		widgets={
			'school':Textarea(attrs={'rows':3}),
			'autograph':Textarea(attrs={'rows':3}),
		}

class UserProfileForm_read(ModelForm):
	class Meta:
		model=Userinfo
		fields=['birthday','sex','school','autograph']
		widgets={
			'birthday':TextInput(attrs={'readonly':'readonly'}),
			'sex':TextInput(attrs={'readonly':'readonly'}),
			'school':TextInput(attrs={'readonly':'readonly'}),
			'autograph':TextInput(attrs={'readonly':'readonly'}),
		}

class EmailConfirmForm(Form):
	emailnum_input=IntegerField(label='验证码:',min_value=100000,max_value=999999)

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth import login,logout,authenticate 
from .models import Userinfo,YZM,Follower,News,Favorites
from blogs.models import Theme
from django.contrib.auth.models import User
from .forms import UserForm,UserProfileForm,EmailConfirmForm,UserProfileForm_read
from PIL import Image
import random,sys,io
from django.core.mail import send_mail
#coding=utf-8

def Storage_pic(request):
	name=request.user.id+'.jpg'
	with open(name,'wb') as pic:
		pic.write(request.FILES['picture'].content)
		pic.close
		return pic
		
def logout_views(request):
	logout(request)
	return HttpResponseRedirect(reverse('blogs:login'))
def register(request):
	if request.method!='POST':
		user_form=UserForm()
		context={'user_form':user_form}
	else:
		user_form=UserForm(data=request.POST)
		if user_form.is_valid():
			email=request.POST['email']
			email_num=request.POST['email_num']
			try:
				email_sql=YZM.objects.get(email=email)
			except:
				return HttpResponse('同一个邮箱只能注册一个帐号!')
			user=user_form.save()
			user.email=email
			user.is_active=True
			user.save()
			Userinfo.objects.create(user=user)
			return render(request,'users/regsuc.html')
	return render(request,'users/register.html',context)

def register_confirm(request):
	email=request.GET['email']
	email_num=random.randint(100000,999999)
	try:
		send_mail('欢迎注册zz的网站','欢迎注册zz的网站,您的注册验证码是: '+str(email_num)+' .','271938333@qq.com',[email],fail_silently=False)
	except:
		return HttpResponse('发生了一些未知的错误...')
	YZM.objects.create(email=email,yzm=email_num)
	
def some_works(request):
	root=sys.path[0]+'/users/map_list.txt'
	lists=[]
	with open(root,'r',encoding='utf-8') as f:
		str_all=f.readlines()
		f.close()
	for str in str_all:
		list=str.split(',')
		lists.append(list)
	context={'lists':lists}
	return render(request,'users/some_works.html',context)
def userinfo(request,user_id):
	page_user=User.objects.get(id=user_id)
	themes=Theme.objects.filter(owner=page_user)
	page_userinfo=Userinfo.objects.get(user=page_user)
	info_read_form=UserProfileForm_read(instance=page_userinfo)
	followers=Follower.objects.filter(focus=page_user)
	focusers=Follower.objects.filter(follower=page_user)
	favorites=Favorites.objects.filter(user=page_user)
	try:
		the_follower=Follower.objects.get(focus=page_user,follower=request.user)
	except:
		the_follower=False
	context={'page_user':page_user,'themes':themes,'page_userinfo':page_userinfo,'info_read_form':info_read_form,'followers':followers,'the_follower':the_follower,'focusers':focusers,'favorites':favorites}
	return render(request,'users/userinfo.html',context)
def ff_list(request,user_id):
	page_user=User.objects.get(id=user_id)
	if request.GET['f'] == 'focusers':
		focusers=Follower.objects.filter(follower=page_user)
		context={'focusers':focusers,'page_user':page_user}
	elif request.GET['f'] == 'followers':
		followers=Follower.objects.filter(focus=page_user)
		context={'followers':followers,'page_user':page_user}
	else:
		return HttpResponse('some errors')
	return render(request,'users/ff_list.html',context)
def alterinfo(request):
	page_user=request.user
	if request.method!='POST':
		userinfo=Userinfo.objects.get(user=page_user)
		infoform=UserProfileForm(instance=userinfo)
		context={'infoform':infoform,'page_user':page_user}
		return render(request,'users/alterinfo.html',context)
	else:
		userinfo=Userinfo.objects.get(user=page_user)
		form=UserProfileForm(request.POST,request.FILES,instance=userinfo)
		if form.is_valid():
			form.save()
		return HttpResponseRedirect(reverse('blogs:index'))
def news(request):
	page_user=request.user
	news=News.objects.filter(user=page_user)
	news_unread=News.objects.filter(user=page_user,status=True)
	if news_unread:
		for new_unread in news_unread:
			new_unread.status=False
			new_unread.save()
	context={'page_user':page_user,'news':news}
	return render(request,'users/news.html',context)
def regsuc(request):
	return render(request,'users/regsuc.html')
def follow(request,user_id):
	user=request.user
	page_user=User.objects.get(id=user_id)
	try:
		the_follower=Follower.objects.get(focus=page_user,follower=user)
		the_follower.delete()
	except:
		Follower.objects.create(focus=page_user,follower=user)
	return HttpResponseRedirect(reverse('users:userinfo',args=[page_user.id]))
def favorite_list(request,user_id):
	page_user=User.objects.get(id=user_id)
	favorites=Favorites.objects.filter(user=page_user)
	context={'favorites':favorites,'page_user':page_user}
	return render(request,'users/favorite_list.html',context)

users/templates/users/alterinfo.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<h3 style="margin-top: 0px;">修改资料:</h3>
<p style="margin-bottom:1px" align="right">
    <a href="{% url 'password_change' %}"><button class="btn btn-default">修改密码</button></a>
</p>
{% endblock header %}
{% block content %}
<div class="col-md-8">

<form method='post' action="{% url 'users:alterinfo' %}" class='form' enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form infoform %}
{% buttons %}
  <button name='submit' class='btn btn-primary'>保存</button>
{% endbuttons %}
  <input type='hidden' name='next' value="{% url 'blogs:index' %}">
</form>
</div>
{% endblock content %}

users/templates/users/base.html
{% load bootstrap3 %}
{% load static %}
<!DOCTYPE html>
<html lang='en'>

<head>
  <meta charset='utf-8'>
  <meta http-equiv='X-UA-Compatible' content='IE=edge'>
  <meta name='viewport' content='width=device-width,initial-scale=1,maximum-scale=1, user-scalable=no'>
	
  <title>zz' website</title>
	
  {% bootstrap_css %}
  {% bootstrap_javascript %}
</head>

<body><!-- Static navbar -->
  <nav class='navbar navbar-default navbar-static-top'>
    <div class='container'>
	  <div class='navbar-header'>
		<button type='button' class='navbar-toggle collapsed' data-toggle='collapse' data-target='#navbar' aria-expanded= 'false' aria-controls='navbar'>
		</button>
	    <a class='navbar-brand' href="{% url 'blogs:login' %}">seLzzf</a>
		<a class='navbar-brand' href="{% url 'users:register' %}">注册帐号</a>
		
		<a class='navbar-brand ' href="{% url 'users:some_works' %}">爬虫小作品</a>
	  </div>
	</div>  
  </nav>
  <div class='container'>
    <div class='page-header'>
      {% block header %}{% endblock header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
	</div>
  </div><!-- /container --> 
</body>

</html>

users/templates/users/favorite_list.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
{% endblock header %}

{% block content %}

{% for favorite in favorites %}
<a href="{% url 'blogs:theme' page_user.id favorite.theme.id %}">{{favorite.theme}}</a>
{% empty %}
<h4>没有任何收藏</h4>
{% endfor %}



{% endblock content %}

users/templates/users/ff_list.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
{% endblock header %}

{% block content %}
  {% if followers %}
    {% for follower in followers %}
	  <li><a href="{% url 'users:userinfo' follower.follower.id %}">{{follower.follower}}</li></a>
	{% empty %}
	  <h3>暂未关注任何用户</h3>
	{% endfor %}
  {% elif focusers %}
    {% for focuser in focusers %}
	  <li><a href="{% url 'users:userinfo' focuser.focus.id %}">{{focuser.focus}}</li></a>
	{% empty %}
	  <h3>暂未关注任何用户</h3>
	{% endfor %}
  {% else %}
	<h3>what happend?</h3>
  {% endif %}
{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load bootstrap3 %} 
<!-- base.html中引入之后,继承模版并没有引入,需要重新引入    -->

{% block header %}
  <h2>登录selzzf的网站:</h2>
{% endblock header %}

{% block content %}
<div class="col-md-8">
{% if form.errors %}
  <p><h3>用户名或密码错误。</h3></p>
{% endif %}
  <form action="{% url 'users:login' %}" method='post' class='form'>
	{% csrf_token %}
	{% bootstrap_form form %}
	{% buttons %}
	<button name='submit' class='btn btn-primary'>登录</button> &nbsp
	<a href="{% url 'password_reset' %}">忘记密码?</a>
	{% endbuttons %}

	<input type='hidden' name='next' value="{% url 'blogs:index' %}">
  </form>
</div>

<div class="col-md-4">
帐号 : 111
<br/>
密码 : 1111aaaa
</div>
{% endblock content %}

users/templates/users/news.html
{% extends "blogs/base.html" %}
{% load static %}

{% block header %}
{% endblock header %}

{% block content %}

{% for new in news %}
  <li>{{ new.news }}</li>
{% empty %}
  暂时没有消息
{% endfor %}

{% endblock content %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load bootstrap3 %}
{% load static %}
<script src="{% static 'js/test.js' %}"></script>

{% block header %}
  <h3>注册帐号:<h3>
{% endblock header %}

{% block content %}
<div class="col-md-8">
<form method='post' action="{% url 'users:register' %}" class='form' enctype="multipart/form-data">
  {% csrf_token %}
  {% bootstrap_form user_form %}
  
  <label>邮箱地址</label>        <br/>
  <input id='email_num' class="form-control" type='email' name='email' placeholder='输入邮箱' />      <br/>
  
  <input class="form" type='text' maxlength=6 name='email_num' placeholder='邮箱验证码' /> 
  
  <input id='send_email' class="btn" type='button' value='发送邮件' />
  
  
  {% buttons %}
    <button name='submit' class='btn btn-primary'>注册</button>
  {% endbuttons %}
  <input type='hidden' name='next' value="{% url 'users:regsuc' %}">
</form>
</div>

<script src="{% static 'js/test.js' %}"></script>

{% endblock content %}

users/templates/users/register_confirm.html
{% extends 'users/base.html' %}
{% load bootstrap3 %}

{% block header %}{% endblock header %}

{% block content %}
<h4>请输入您收到的验证码:<h4>
<form method='POST' action="{% url 'users:register_confirm' %}">
  {% csrf_token %}
  {% bootstrap_form form %}
  <input type='hidden' name='user_id' value={{user_id}}>
  <button name='submit' class='btn btn-primary'>提交
  </button> &nbsp
</form>
{% endblock content %}

users/templates/users/regsuc.html
{% extends 'users/base.html' %}

{% block header %}<h4>注册成功<h4>{% endblock header %}
{% block content %}
<a href="{% url 'users:login' %}">返回登录页面</a>
{% endblock content %}

users/templates/users/some_works.html
{% extends 'users/base.html' %}
{% load bootstrap3 %}
{% load static %}
{% load diy_filter %}

{% block header %}{% endblock header %}

{% block content %}

<div>
  <h4>魔兽rpg地图每日更新:</h4>
  <table class='table table-hover table-striped table-border'>
    <thead>
	  <tr>
	  <th>日期</th>
	  <th>地图</th>
	  <th>链接</th>
	  <th>类型</th>
	  </tr>
	</thead>
	
	<tbody>
	{% for list in lists %}
	<tr>
      <td>{{ list | x_in_list:0 }}</td>
	  <td><a href="{{ list | x_in_list:2 }}">{{ list | x_in_list:1 }}<a></td>
	  <td>{{ list | x_in_list:2 }}</td>
	  <td>{{ list | x_in_list:3 }}</td>
	</tr>
	{% empty %}
	{% endfor %}
    </tbody>
  </table>
  <small style="float:right;">——爬取自 http://war3.uuu9.com </small>
</div>

<Br/><Br/>

<div>
  <h4>爬取贴吧头像:</h4>
  <img width="1120" height="630" src="{% static 'images/贴吧头像.jpg' %}"/>

<Br/><Br/>

  <h4>爬取QQ好友头像:</h4>
  <img src="{% static 'images/QQ好友头像.jpg' %}"/>
</div>

{% endblock content %}

users/templates/users/userinfo.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  
  
{% if user == page_user %}
  <p style="margin-bottom:1px " align="right">
    <a href="{% url 'users:alterinfo' %}"><button class="btn btn-default">修改信息</button></a>
  </p>
{% else %}
  <p style="margin-bottom:1px " align="right">
      <a href="{% url 'users:follow' page_user.id %}">
	    {% if the_follower in followers %}
	    <button class="btn btn-default">取消关注</button>
	    {% else %}
	    <button class="btn btn-default">关注</button>
	    {% endif %}	
	  </a>
  </p>
{% endif %}

{% endblock header %}

{% block content %}

<div class="col-md-5">
  <div class='panel panel-default'>
  
    <div style="border:1px padding:2px" class='text-center'>
	  <img src="{{ page_userinfo.pic.url }}" alt='pic' height="80" width="80" />
    </div>
	
	<div class='panel-body'>
	  <div>
	    <h4 class='text-center' style="margin-top: 0px;">{{page_user.username}}</h4>
	  </div>
	  <form method='post' class='form' enctype="multipart/form-data">
        {% csrf_token %}
        {% bootstrap_form info_read_form %}
      </form>
    </div>
	
  </div>
</div>

<div class="col-md-7">
  <div class='panel panel-default'>
    <h4>
    <div class='panel-body'>
	  {% if page_userinfo.sex == '男' %}他{% else %}她{% endif %}的主题 : <a href="{% url 'blogs:themes' page_user.id %}" >{{ themes.count }}</a>
    </div>
	<div class='panel-body'>
	  {% if page_userinfo.sex == '男' %}他{% else %}她{% endif %}的收藏 : <a href="{% url 'users:favorite_list' page_user.id %}">{{ favorites.count }}</a>
    </div>
	<div class='panel-body'>
	  {% if page_userinfo.sex == '男' %}他{% else %}她{% endif %}的关注 : <a href="{% url 'users:ff_list' page_user.id %}?f=focusers">{{ focusers.count }}</a>
    </div>
	<div class='panel-body'>
	  {% if page_userinfo.sex == '男' %}他{% else %}她{% endif %}的粉丝 : <a href="{% url 'users:ff_list' page_user.id %}?f=followers">{{ followers.count }}</a>
    </div>
	</h4>
  </div>
</div>

{% endblock content %}