blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    url(r'^admin/', admin.site.urls),
	url(r'^users/',include('users.urls',namespace='users')),
	url(r'^users/', include('django.contrib.auth.urls')),
	url(r'^comments/',include('comments.urls',namespace='comments')),
	url(r'^message/',include('message.urls',namespace='message')),
	url(r'^notes/',include('notes.urls',namespace='notes')),
	url(r'^action/',include('action.urls',namespace='action')),
	url(r'',include('blogs.urls',namespace='blogs')),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

message/urls.py
from django.conf.urls import url
from . import views

urlpatterns=[
	url(r'^(?P<user_id>\d+)/$',views.message,name='message'),
	url(r'^message_privacy/$',views.message_privacy,name='message_privacy'),
	url(r'^delete/(?P<user_id>\d+)/(?P<message_id>\d+)/$',views.message_delete,name='message_delete'),
]

users/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login

urlpatterns=[
	url(r'^login/$',login,{'template_name':'users/login.html'},name='login'),
	url(r'^logout/$',views.logout_views,name='logout'),
	url(r'^register/$',views.register,name='register'),
	url(r'^some_works/$',views.some_works,name='some_works'),
	url(r'^register_confirm/$',views.register_confirm,name='register_confirm'),
	url(r'^userinfo/(?P<user_id>\d+)/$',views.userinfo,name='userinfo'),
	url(r'^news/$',views.news,name='news'),
	url(r'^user_ff_list/(?P<user_id>\d+)/',views.ff_list,name='ff_list'),
	url(r'^alterinfo/$',views.alterinfo,name='alterinfo'),
	url(r'^regsuc/$',views.regsuc,name='regsuc'),
	url(r'^follow/(?P<user_id>\d+)/$',views.follow,name='follow'),
	url(r'^favorite_list/(?P<user_id>\d+)/$',views.favorite_list,name='favorite_list'),
	
]

message/models.py
from django.db import models
from django.contrib.auth.models import User

class To_Message(models.Model):
	owner=models.OneToOneField(User)
	to_message=models.TextField(default='留言板')
	设为私密=models.BooleanField(default=False)
	def __str__(self):
		return self.to_message
class Message(models.Model):
	t_m=models.ForeignKey(To_Message)
	giver=models.ForeignKey(User)
	message=models.TextField('写留言:')
	date_added=models.DateTimeField(auto_now_add=True)
	私密留言=models.BooleanField(default=False)
	def __str__(self):
		return self.message

message/forms.py
from django import forms
from .models import Message

class MessageForm(forms.ModelForm):
	class Meta:
		model=Message
		fields=['message','私密留言']
		lables={''}

message/views.py
from django.shortcuts import render
from .models import To_Message,Message
from django.http import HttpResponseRedirect,Http404,HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from .forms import MessageForm

def message(request,user_id):
	page_user=User.objects.get(id=user_id)
	request_user=request.user
	try:
		T_M=To_Message.objects.get(owner=page_user)
	except:
		T_M=To_Message(owner=page_user,to_message='留言板',设为私密='False')
		T_M.save()
	if request.method=='POST':
		form=MessageForm(data=request.POST)
		if form.is_valid():
			new_message=form.save(commit=False)
			new_message.t_m=T_M
			new_message.giver=request_user
			new_message.save()
			return HttpResponseRedirect(reverse('message:message',args=[page_user.id]))
	else:
		if request_user==page_user:
			messages=Message.objects.filter(t_m=T_M)
		elif T_M.设为私密==True:
			return HttpResponse('你没有访问权限')
		else:
			message1=Message.objects.filter(t_m=T_M,私密留言=False)
			message2=Message.objects.filter(t_m=T_M,私密留言=True,giver=request_user)
			messages=message1|message2
		message_form=MessageForm
		context={'request_user':request_user,'page_user':page_user,'T_M':T_M,'messages':messages,'message_form':message_form}
		return render(request,'message/message.html',context)
		
def message_privacy(request):
	user=request.user
	T_M=To_Message.objects.get(owner=user)
	if T_M.设为私密:
		T_M.设为私密=False
		T_M.save()
	else:
		T_M.设为私密=True
		T_M.save()
	context={'page_user':user,}
	return render(request,'blogs/privacysuc.html',context)
	
def message_delete(request,user_id,message_id):
	msg=Message.objects.get(id=message_id)
	page_user=User.objects.get(id=user_id)
	if request.user == msg.giver or request.user == page_user:
		msg.delete()
		return HttpResponseRedirect(reverse('message:message',args=[page_user.id]))
	else:
		return

message/templates/message/message.html
{% extends "blogs/base.html" %}  
{% load bootstrap3 %}
{% block header %}
<div>
  <h4>留言板:</h4>
  {% if user == page_user %}
    {% if T_M.设为私密 %}
	  当前权限:仅自己可见<a href="{% url 'message:message_privacy' %}" style="float:right;">设为公开</a>
	{% else %}
	  当前权限:所有人可见<a href="{% url 'message:message_privacy' %}" style="float:right;">设为私密</a>
	{% endif %}
  {% endif %}  
</div>
{% endblock header %}

{% block content %}
<div class='col-md-8'>

  {% for message in messages %}
  <div class='panel panel-default'>
    <div class='panel-body'>
	  <h4>{{ message.message|linebreaks }}<h4>
    </div>
    <div class='panel-heading'>
	  <a href="{% url 'users:userinfo' message.giver.id %}">{{message.giver}}</a>
	  <span style="float:right;">
	    {% if message.私密留言 %}
		  仅彼此可见
		{% endif %}
		&nbsp&nbsp&nbsp&nbsp&nbsp
        {{message.date_added|date:'Y-m-d H:i:s'}}
		&nbsp&nbsp&nbsp&nbsp&nbsp
	    {% if page_user == request_user %}
	      <a href="{% url 'message:message_delete' page_user.id message.id %}">删除</a>
	    {% endif %}
	  </span>
    </div>
  </div>
  {% empty %}
    <h3><li>暂时还没有评论。</li></h3>
  {% endfor %}
  
<hr/>
  
  <div>
  <h4></h4>
  <form method='POST' action="{% url 'message:message' page_user.id %}">
    {% csrf_token %}
    {% bootstrap_form message_form %}
    {% buttons %}
	<button name='submit' class='btn btn-primary'>提交</button>
	{% endbuttons %}
  </form>
  </div>
  
</div>
  
{% endblock content %}